version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 22.0
        commands:
            - npm install
            - npm install -g @angular/cli
    pre_build:
        commands:
            - echo S3 Bucket= $S3_BUCKET
            - echo Cloudfront Distribution= $CLOUDFRONT_DISTRIBUTION
    build:
        commands:
            - ng build
    post_build:
         commands:
            - aws s3 sync dist/frontend/browser $S3_BUCKET
            - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"